PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

DELETE {
    GRAPH ?g {
        ?subcase ext:bevatDocumentversie ?document .
    }
}
INSERT {
    GRAPH ?g {
        ?submissionActivity a ext:Indieningsactiviteit ;
            mu:uuid ?uuid ;
            prov:generated ?document ;
            ext:indieningVindtPlaatsTijdens ?subcase .
        ?agendaActivity prov:wasInformedBy ?submissionActivity .
    }
}
WHERE {
    GRAPH ?g {
        ?subcase ext:bevatDocumentversie ?document .
        OPTIONAL { 
            ?agendaActivity a besluitvorming:Agendering ;
                besluitvorming:vindtPlaatsTijdens ?subcase .
        }
    }
    VALUES (?submissionActivity ?uuid ?subcase) {
        # SUBMISSION_ACTIVITY_VALUES_PLACEHOLDER
    }
}