PREFIX besluitvorming: <http://data.vlaanderen.be/ns/besluitvorming#>
PREFIX prov: <http://www.w3.org/ns/prov#>

DELETE {
    GRAPH ?g {
          # SUBCASE_PLACEHOLDER ext:bevatDocumentversie ?document .
    }
}
INSERT {
    GRAPH ?g {
        # SUBMISSION_ACTIVITY_TRIPLES_PLACEHOLDER
        # SUBMISSION_ACTIVITY_PLACEHOLDER prov:generated ?document ;
            ext:indieningVindtPlaatsTijdens # SUBCASE_PLACEHOLDER .
        ?agendaActivity prov:wasInformedBy # SUBMISSION_ACTIVITY_PLACEHOLDER .
    }
}
WHERE {
    GRAPH ?g {
        # SUBCASE_PLACEHOLDER ext:bevatDocumentversie ?document .
        OPTIONAL { 
            ?agendaActivity a besluitvorming:Agendering .
                besluitvorming:vindtPlaatsTijdens # SUBCASE_PLACEHOLDER .
        }
    }
}